### ISSUE TITLE
REST API endpoints' names in the liks section should follow the standard

### ISSUE THREAD

**Issue by pesarkhobeee** [Restfulness/Restfulness-core-api#16]
In the Restful design, we are not putting verbs inside the URL, so all the endpoints in trhe below picture
<img width="1413" alt="Screenshot 2020-10-16 at 19 17 39" src="https://user-images.githubusercontent.com/147461/96289038-a4656280-0fe4-11eb-814a-8ab47f02d6fd.png">

should change to 
/links
because we are using HTTP request methods:

> The action should be indicated by the HTTP request method that we’re making. The most common methods include GET, POST, PUT, and DELETE.
https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/

Also, we don't need to two get endpoint! both functionalities can summarize to one endpoint!

**Comment by farzadi** [comment]
For fetching link id's I think it's good to have an API that returns just link ids in an array and with another API fetch them by their id's one by one.

**Comment by pesarkhobeee** [comment]
@farzadi I believe we should add pagination in the near future to that and also send minimal information about each  bookmark like id and url then if users or applications need more information they can ask from separate API endpoint
